%% coding: latin-1
%%: 实现
-module(cfg_petLevelProperty_chs).
-compile(export_all).
-include("cfg_petLevelProperty.hrl").
-include("logger.hrl").

getRow(1)->
    #petLevelPropertyCfg {
    level = 1,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 20,
    mPRecover = 20
    };
getRow(2)->
    #petLevelPropertyCfg {
    level = 2,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 30,
    mPRecover = 30
    };
getRow(3)->
    #petLevelPropertyCfg {
    level = 3,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 40,
    mPRecover = 40
    };
getRow(4)->
    #petLevelPropertyCfg {
    level = 4,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 50,
    mPRecover = 50
    };
getRow(5)->
    #petLevelPropertyCfg {
    level = 5,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 60,
    mPRecover = 60
    };
getRow(6)->
    #petLevelPropertyCfg {
    level = 6,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 70,
    mPRecover = 70
    };
getRow(7)->
    #petLevelPropertyCfg {
    level = 7,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 80,
    mPRecover = 80
    };
getRow(8)->
    #petLevelPropertyCfg {
    level = 8,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 90,
    mPRecover = 90
    };
getRow(9)->
    #petLevelPropertyCfg {
    level = 9,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 100,
    mPRecover = 100
    };
getRow(10)->
    #petLevelPropertyCfg {
    level = 10,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 110,
    mPRecover = 110
    };
getRow(11)->
    #petLevelPropertyCfg {
    level = 11,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 0,
    physicalAttack = 0,
    magicAttack = 0,
    physicalDefence = 0,
    magicDefence = 0,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 120,
    mPRecover = 120
    };
getRow(12)->
    #petLevelPropertyCfg {
    level = 12,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 6195,
    physicalAttack = 103,
    magicAttack = 103,
    physicalDefence = 64,
    magicDefence = 64,
    hitLevel = 38,
    criticalLevel = 51,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 130,
    mPRecover = 130
    };
getRow(13)->
    #petLevelPropertyCfg {
    level = 13,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 6464,
    physicalAttack = 107,
    magicAttack = 107,
    physicalDefence = 67,
    magicDefence = 67,
    hitLevel = 40,
    criticalLevel = 54,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 140,
    mPRecover = 140
    };
getRow(14)->
    #petLevelPropertyCfg {
    level = 14,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 6734,
    physicalAttack = 112,
    magicAttack = 112,
    physicalDefence = 70,
    magicDefence = 70,
    hitLevel = 42,
    criticalLevel = 56,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 150,
    mPRecover = 150
    };
getRow(15)->
    #petLevelPropertyCfg {
    level = 15,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 7003,
    physicalAttack = 116,
    magicAttack = 116,
    physicalDefence = 72,
    magicDefence = 72,
    hitLevel = 43,
    criticalLevel = 57,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 160,
    mPRecover = 160
    };
getRow(16)->
    #petLevelPropertyCfg {
    level = 16,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 7272,
    physicalAttack = 121,
    magicAttack = 121,
    physicalDefence = 75,
    magicDefence = 75,
    hitLevel = 45,
    criticalLevel = 60,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 170,
    mPRecover = 170
    };
getRow(17)->
    #petLevelPropertyCfg {
    level = 17,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 7542,
    physicalAttack = 125,
    magicAttack = 125,
    physicalDefence = 78,
    magicDefence = 78,
    hitLevel = 46,
    criticalLevel = 62,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 180,
    mPRecover = 180
    };
getRow(18)->
    #petLevelPropertyCfg {
    level = 18,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 7811,
    physicalAttack = 130,
    magicAttack = 130,
    physicalDefence = 81,
    magicDefence = 81,
    hitLevel = 48,
    criticalLevel = 65,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 190,
    mPRecover = 190
    };
getRow(19)->
    #petLevelPropertyCfg {
    level = 19,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 8080,
    physicalAttack = 134,
    magicAttack = 134,
    physicalDefence = 84,
    magicDefence = 84,
    hitLevel = 50,
    criticalLevel = 67,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 200,
    mPRecover = 200
    };
getRow(20)->
    #petLevelPropertyCfg {
    level = 20,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 8350,
    physicalAttack = 139,
    magicAttack = 139,
    physicalDefence = 86,
    magicDefence = 86,
    hitLevel = 52,
    criticalLevel = 69,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 210,
    mPRecover = 210
    };
getRow(21)->
    #petLevelPropertyCfg {
    level = 21,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 8619,
    physicalAttack = 143,
    magicAttack = 143,
    physicalDefence = 89,
    magicDefence = 89,
    hitLevel = 54,
    criticalLevel = 72,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 220,
    mPRecover = 220
    };
getRow(22)->
    #petLevelPropertyCfg {
    level = 22,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 8889,
    physicalAttack = 148,
    magicAttack = 148,
    physicalDefence = 92,
    magicDefence = 92,
    hitLevel = 55,
    criticalLevel = 73,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 230,
    mPRecover = 230
    };
getRow(23)->
    #petLevelPropertyCfg {
    level = 23,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 9158,
    physicalAttack = 152,
    magicAttack = 152,
    physicalDefence = 95,
    magicDefence = 95,
    hitLevel = 57,
    criticalLevel = 76,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 240,
    mPRecover = 240
    };
getRow(24)->
    #petLevelPropertyCfg {
    level = 24,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 9427,
    physicalAttack = 157,
    magicAttack = 157,
    physicalDefence = 98,
    magicDefence = 98,
    hitLevel = 58,
    criticalLevel = 78,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 250,
    mPRecover = 250
    };
getRow(25)->
    #petLevelPropertyCfg {
    level = 25,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 9697,
    physicalAttack = 161,
    magicAttack = 161,
    physicalDefence = 101,
    magicDefence = 101,
    hitLevel = 60,
    criticalLevel = 80,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 260,
    mPRecover = 260
    };
getRow(26)->
    #petLevelPropertyCfg {
    level = 26,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 9966,
    physicalAttack = 166,
    magicAttack = 166,
    physicalDefence = 103,
    magicDefence = 103,
    hitLevel = 62,
    criticalLevel = 83,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 270,
    mPRecover = 270
    };
getRow(27)->
    #petLevelPropertyCfg {
    level = 27,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 10235,
    physicalAttack = 170,
    magicAttack = 170,
    physicalDefence = 106,
    magicDefence = 106,
    hitLevel = 63,
    criticalLevel = 85,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 280,
    mPRecover = 280
    };
getRow(28)->
    #petLevelPropertyCfg {
    level = 28,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 10505,
    physicalAttack = 175,
    magicAttack = 175,
    physicalDefence = 109,
    magicDefence = 109,
    hitLevel = 65,
    criticalLevel = 87,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 290,
    mPRecover = 290
    };
getRow(29)->
    #petLevelPropertyCfg {
    level = 29,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 10774,
    physicalAttack = 179,
    magicAttack = 179,
    physicalDefence = 112,
    magicDefence = 112,
    hitLevel = 67,
    criticalLevel = 89,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 300,
    mPRecover = 300
    };
getRow(30)->
    #petLevelPropertyCfg {
    level = 30,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 11043,
    physicalAttack = 184,
    magicAttack = 184,
    physicalDefence = 115,
    magicDefence = 115,
    hitLevel = 69,
    criticalLevel = 91,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 310,
    mPRecover = 310
    };
getRow(31)->
    #petLevelPropertyCfg {
    level = 31,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 11313,
    physicalAttack = 188,
    magicAttack = 188,
    physicalDefence = 117,
    magicDefence = 117,
    hitLevel = 71,
    criticalLevel = 94,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 320,
    mPRecover = 320
    };
getRow(32)->
    #petLevelPropertyCfg {
    level = 32,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 11582,
    physicalAttack = 193,
    magicAttack = 193,
    physicalDefence = 120,
    magicDefence = 120,
    hitLevel = 72,
    criticalLevel = 96,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 330,
    mPRecover = 330
    };
getRow(33)->
    #petLevelPropertyCfg {
    level = 33,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 11852,
    physicalAttack = 197,
    magicAttack = 197,
    physicalDefence = 123,
    magicDefence = 123,
    hitLevel = 73,
    criticalLevel = 99,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 340,
    mPRecover = 340
    };
getRow(34)->
    #petLevelPropertyCfg {
    level = 34,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 12121,
    physicalAttack = 202,
    magicAttack = 202,
    physicalDefence = 126,
    magicDefence = 126,
    hitLevel = 75,
    criticalLevel = 101,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 350,
    mPRecover = 350
    };
getRow(35)->
    #petLevelPropertyCfg {
    level = 35,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 12390,
    physicalAttack = 206,
    magicAttack = 206,
    physicalDefence = 129,
    magicDefence = 129,
    hitLevel = 77,
    criticalLevel = 102,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 360,
    mPRecover = 360
    };
getRow(36)->
    #petLevelPropertyCfg {
    level = 36,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 12660,
    physicalAttack = 211,
    magicAttack = 211,
    physicalDefence = 131,
    magicDefence = 131,
    hitLevel = 79,
    criticalLevel = 105,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 370,
    mPRecover = 370
    };
getRow(37)->
    #petLevelPropertyCfg {
    level = 37,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 12929,
    physicalAttack = 215,
    magicAttack = 215,
    physicalDefence = 134,
    magicDefence = 134,
    hitLevel = 80,
    criticalLevel = 107,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 380,
    mPRecover = 380
    };
getRow(38)->
    #petLevelPropertyCfg {
    level = 38,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 13198,
    physicalAttack = 219,
    magicAttack = 219,
    physicalDefence = 137,
    magicDefence = 137,
    hitLevel = 82,
    criticalLevel = 110,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 390,
    mPRecover = 390
    };
getRow(39)->
    #petLevelPropertyCfg {
    level = 39,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 13468,
    physicalAttack = 224,
    magicAttack = 224,
    physicalDefence = 140,
    magicDefence = 140,
    hitLevel = 84,
    criticalLevel = 112,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 400,
    mPRecover = 400
    };
getRow(40)->
    #petLevelPropertyCfg {
    level = 40,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 13737,
    physicalAttack = 228,
    magicAttack = 228,
    physicalDefence = 143,
    magicDefence = 143,
    hitLevel = 86,
    criticalLevel = 114,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 410,
    mPRecover = 410
    };
getRow(41)->
    #petLevelPropertyCfg {
    level = 41,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 14006,
    physicalAttack = 233,
    magicAttack = 233,
    physicalDefence = 145,
    magicDefence = 145,
    hitLevel = 87,
    criticalLevel = 116,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 420,
    mPRecover = 420
    };
getRow(42)->
    #petLevelPropertyCfg {
    level = 42,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 14276,
    physicalAttack = 237,
    magicAttack = 237,
    physicalDefence = 148,
    magicDefence = 148,
    hitLevel = 88,
    criticalLevel = 118,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 430,
    mPRecover = 430
    };
getRow(43)->
    #petLevelPropertyCfg {
    level = 43,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 14545,
    physicalAttack = 242,
    magicAttack = 242,
    physicalDefence = 151,
    magicDefence = 151,
    hitLevel = 90,
    criticalLevel = 121,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 440,
    mPRecover = 440
    };
getRow(44)->
    #petLevelPropertyCfg {
    level = 44,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 14815,
    physicalAttack = 246,
    magicAttack = 246,
    physicalDefence = 154,
    magicDefence = 154,
    hitLevel = 92,
    criticalLevel = 123,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 450,
    mPRecover = 450
    };
getRow(45)->
    #petLevelPropertyCfg {
    level = 45,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 15084,
    physicalAttack = 251,
    magicAttack = 251,
    physicalDefence = 157,
    magicDefence = 157,
    hitLevel = 94,
    criticalLevel = 125,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 460,
    mPRecover = 460
    };
getRow(46)->
    #petLevelPropertyCfg {
    level = 46,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 15353,
    physicalAttack = 255,
    magicAttack = 255,
    physicalDefence = 159,
    magicDefence = 159,
    hitLevel = 96,
    criticalLevel = 128,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 470,
    mPRecover = 470
    };
getRow(47)->
    #petLevelPropertyCfg {
    level = 47,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 15623,
    physicalAttack = 260,
    magicAttack = 260,
    physicalDefence = 162,
    magicDefence = 162,
    hitLevel = 97,
    criticalLevel = 129,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 480,
    mPRecover = 480
    };
getRow(48)->
    #petLevelPropertyCfg {
    level = 48,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 15892,
    physicalAttack = 264,
    magicAttack = 264,
    physicalDefence = 165,
    magicDefence = 165,
    hitLevel = 99,
    criticalLevel = 132,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 490,
    mPRecover = 490
    };
getRow(49)->
    #petLevelPropertyCfg {
    level = 49,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 16161,
    physicalAttack = 269,
    magicAttack = 269,
    physicalDefence = 168,
    magicDefence = 168,
    hitLevel = 101,
    criticalLevel = 134,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 500,
    mPRecover = 500
    };
getRow(50)->
    #petLevelPropertyCfg {
    level = 50,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 16431,
    physicalAttack = 273,
    magicAttack = 273,
    physicalDefence = 171,
    magicDefence = 171,
    hitLevel = 102,
    criticalLevel = 136,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 510,
    mPRecover = 510
    };
getRow(51)->
    #petLevelPropertyCfg {
    level = 51,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 20376,
    physicalAttack = 617,
    magicAttack = 617,
    physicalDefence = 385,
    magicDefence = 385,
    hitLevel = 154,
    criticalLevel = 231,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 520,
    mPRecover = 520
    };
getRow(52)->
    #petLevelPropertyCfg {
    level = 52,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 20740,
    physicalAttack = 628,
    magicAttack = 628,
    physicalDefence = 392,
    magicDefence = 392,
    hitLevel = 157,
    criticalLevel = 235,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 530,
    mPRecover = 530
    };
getRow(53)->
    #petLevelPropertyCfg {
    level = 53,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 21104,
    physicalAttack = 639,
    magicAttack = 639,
    physicalDefence = 399,
    magicDefence = 399,
    hitLevel = 159,
    criticalLevel = 239,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 540,
    mPRecover = 540
    };
getRow(54)->
    #petLevelPropertyCfg {
    level = 54,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 21468,
    physicalAttack = 650,
    magicAttack = 650,
    physicalDefence = 406,
    magicDefence = 406,
    hitLevel = 162,
    criticalLevel = 243,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 550,
    mPRecover = 550
    };
getRow(55)->
    #petLevelPropertyCfg {
    level = 55,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 21832,
    physicalAttack = 661,
    magicAttack = 661,
    physicalDefence = 413,
    magicDefence = 413,
    hitLevel = 165,
    criticalLevel = 248,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 560,
    mPRecover = 560
    };
getRow(56)->
    #petLevelPropertyCfg {
    level = 56,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 22195,
    physicalAttack = 672,
    magicAttack = 672,
    physicalDefence = 420,
    magicDefence = 420,
    hitLevel = 168,
    criticalLevel = 252,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 570,
    mPRecover = 570
    };
getRow(57)->
    #petLevelPropertyCfg {
    level = 57,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 22559,
    physicalAttack = 683,
    magicAttack = 683,
    physicalDefence = 427,
    magicDefence = 427,
    hitLevel = 170,
    criticalLevel = 256,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 580,
    mPRecover = 580
    };
getRow(58)->
    #petLevelPropertyCfg {
    level = 58,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 22923,
    physicalAttack = 694,
    magicAttack = 694,
    physicalDefence = 434,
    magicDefence = 434,
    hitLevel = 173,
    criticalLevel = 260,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 590,
    mPRecover = 590
    };
getRow(59)->
    #petLevelPropertyCfg {
    level = 59,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 23287,
    physicalAttack = 705,
    magicAttack = 705,
    physicalDefence = 441,
    magicDefence = 441,
    hitLevel = 176,
    criticalLevel = 264,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 600,
    mPRecover = 600
    };
getRow(60)->
    #petLevelPropertyCfg {
    level = 60,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 23651,
    physicalAttack = 716,
    magicAttack = 716,
    physicalDefence = 447,
    magicDefence = 447,
    hitLevel = 179,
    criticalLevel = 268,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 610,
    mPRecover = 610
    };
getRow(61)->
    #petLevelPropertyCfg {
    level = 61,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 24015,
    physicalAttack = 727,
    magicAttack = 727,
    physicalDefence = 454,
    magicDefence = 454,
    hitLevel = 181,
    criticalLevel = 272,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 620,
    mPRecover = 620
    };
getRow(62)->
    #petLevelPropertyCfg {
    level = 62,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 24379,
    physicalAttack = 738,
    magicAttack = 738,
    physicalDefence = 461,
    magicDefence = 461,
    hitLevel = 184,
    criticalLevel = 277,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 630,
    mPRecover = 630
    };
getRow(63)->
    #petLevelPropertyCfg {
    level = 63,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 24742,
    physicalAttack = 749,
    magicAttack = 749,
    physicalDefence = 468,
    magicDefence = 468,
    hitLevel = 187,
    criticalLevel = 281,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 640,
    mPRecover = 640
    };
getRow(64)->
    #petLevelPropertyCfg {
    level = 64,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 25106,
    physicalAttack = 760,
    magicAttack = 760,
    physicalDefence = 475,
    magicDefence = 475,
    hitLevel = 190,
    criticalLevel = 285,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 650,
    mPRecover = 650
    };
getRow(65)->
    #petLevelPropertyCfg {
    level = 65,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 25470,
    physicalAttack = 771,
    magicAttack = 771,
    physicalDefence = 482,
    magicDefence = 482,
    hitLevel = 192,
    criticalLevel = 289,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 660,
    mPRecover = 660
    };
getRow(66)->
    #petLevelPropertyCfg {
    level = 66,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 25834,
    physicalAttack = 782,
    magicAttack = 782,
    physicalDefence = 489,
    magicDefence = 489,
    hitLevel = 195,
    criticalLevel = 293,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 670,
    mPRecover = 670
    };
getRow(67)->
    #petLevelPropertyCfg {
    level = 67,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 26198,
    physicalAttack = 793,
    magicAttack = 793,
    physicalDefence = 496,
    magicDefence = 496,
    hitLevel = 198,
    criticalLevel = 297,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 680,
    mPRecover = 680
    };
getRow(68)->
    #petLevelPropertyCfg {
    level = 68,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 26562,
    physicalAttack = 804,
    magicAttack = 804,
    physicalDefence = 503,
    magicDefence = 503,
    hitLevel = 201,
    criticalLevel = 301,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 690,
    mPRecover = 690
    };
getRow(69)->
    #petLevelPropertyCfg {
    level = 69,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 26926,
    physicalAttack = 815,
    magicAttack = 815,
    physicalDefence = 509,
    magicDefence = 509,
    hitLevel = 203,
    criticalLevel = 305,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 700,
    mPRecover = 700
    };
getRow(70)->
    #petLevelPropertyCfg {
    level = 70,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 27290,
    physicalAttack = 826,
    magicAttack = 826,
    physicalDefence = 516,
    magicDefence = 516,
    hitLevel = 206,
    criticalLevel = 310,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 710,
    mPRecover = 710
    };
getRow(71)->
    #petLevelPropertyCfg {
    level = 71,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 27653,
    physicalAttack = 837,
    magicAttack = 837,
    physicalDefence = 523,
    magicDefence = 523,
    hitLevel = 209,
    criticalLevel = 314,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 720,
    mPRecover = 720
    };
getRow(72)->
    #petLevelPropertyCfg {
    level = 72,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 28017,
    physicalAttack = 848,
    magicAttack = 848,
    physicalDefence = 530,
    magicDefence = 530,
    hitLevel = 212,
    criticalLevel = 318,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 730,
    mPRecover = 730
    };
getRow(73)->
    #petLevelPropertyCfg {
    level = 73,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 28381,
    physicalAttack = 860,
    magicAttack = 860,
    physicalDefence = 537,
    magicDefence = 537,
    hitLevel = 214,
    criticalLevel = 322,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 740,
    mPRecover = 740
    };
getRow(74)->
    #petLevelPropertyCfg {
    level = 74,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 28745,
    physicalAttack = 871,
    magicAttack = 871,
    physicalDefence = 544,
    magicDefence = 544,
    hitLevel = 217,
    criticalLevel = 326,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 750,
    mPRecover = 750
    };
getRow(75)->
    #petLevelPropertyCfg {
    level = 75,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 29109,
    physicalAttack = 882,
    magicAttack = 882,
    physicalDefence = 551,
    magicDefence = 551,
    hitLevel = 220,
    criticalLevel = 330,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 760,
    mPRecover = 760
    };
getRow(76)->
    #petLevelPropertyCfg {
    level = 76,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 29473,
    physicalAttack = 893,
    magicAttack = 893,
    physicalDefence = 558,
    magicDefence = 558,
    hitLevel = 223,
    criticalLevel = 334,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 770,
    mPRecover = 770
    };
getRow(77)->
    #petLevelPropertyCfg {
    level = 77,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 29837,
    physicalAttack = 904,
    magicAttack = 904,
    physicalDefence = 565,
    magicDefence = 565,
    hitLevel = 226,
    criticalLevel = 339,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 780,
    mPRecover = 780
    };
getRow(78)->
    #petLevelPropertyCfg {
    level = 78,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 30200,
    physicalAttack = 915,
    magicAttack = 915,
    physicalDefence = 571,
    magicDefence = 571,
    hitLevel = 228,
    criticalLevel = 343,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 790,
    mPRecover = 790
    };
getRow(79)->
    #petLevelPropertyCfg {
    level = 79,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 30564,
    physicalAttack = 926,
    magicAttack = 926,
    physicalDefence = 578,
    magicDefence = 578,
    hitLevel = 231,
    criticalLevel = 347,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 800,
    mPRecover = 800
    };
getRow(80)->
    #petLevelPropertyCfg {
    level = 80,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 30928,
    physicalAttack = 937,
    magicAttack = 937,
    physicalDefence = 585,
    magicDefence = 585,
    hitLevel = 234,
    criticalLevel = 351,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 810,
    mPRecover = 810
    };
getRow(81)->
    #petLevelPropertyCfg {
    level = 81,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 31292,
    physicalAttack = 948,
    magicAttack = 948,
    physicalDefence = 592,
    magicDefence = 592,
    hitLevel = 237,
    criticalLevel = 355,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 820,
    mPRecover = 820
    };
getRow(82)->
    #petLevelPropertyCfg {
    level = 82,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 31656,
    physicalAttack = 959,
    magicAttack = 959,
    physicalDefence = 599,
    magicDefence = 599,
    hitLevel = 239,
    criticalLevel = 359,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 830,
    mPRecover = 830
    };
getRow(83)->
    #petLevelPropertyCfg {
    level = 83,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 32020,
    physicalAttack = 970,
    magicAttack = 970,
    physicalDefence = 606,
    magicDefence = 606,
    hitLevel = 242,
    criticalLevel = 363,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 840,
    mPRecover = 840
    };
getRow(84)->
    #petLevelPropertyCfg {
    level = 84,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 32384,
    physicalAttack = 981,
    magicAttack = 981,
    physicalDefence = 613,
    magicDefence = 613,
    hitLevel = 245,
    criticalLevel = 367,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 850,
    mPRecover = 850
    };
getRow(85)->
    #petLevelPropertyCfg {
    level = 85,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 32748,
    physicalAttack = 992,
    magicAttack = 992,
    physicalDefence = 620,
    magicDefence = 620,
    hitLevel = 248,
    criticalLevel = 372,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 860,
    mPRecover = 860
    };
getRow(86)->
    #petLevelPropertyCfg {
    level = 86,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 33111,
    physicalAttack = 1003,
    magicAttack = 1003,
    physicalDefence = 627,
    magicDefence = 627,
    hitLevel = 250,
    criticalLevel = 376,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 870,
    mPRecover = 870
    };
getRow(87)->
    #petLevelPropertyCfg {
    level = 87,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 33475,
    physicalAttack = 1014,
    magicAttack = 1014,
    physicalDefence = 634,
    magicDefence = 634,
    hitLevel = 253,
    criticalLevel = 380,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 880,
    mPRecover = 880
    };
getRow(88)->
    #petLevelPropertyCfg {
    level = 88,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 33839,
    physicalAttack = 1025,
    magicAttack = 1025,
    physicalDefence = 640,
    magicDefence = 640,
    hitLevel = 256,
    criticalLevel = 384,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 890,
    mPRecover = 890
    };
getRow(89)->
    #petLevelPropertyCfg {
    level = 89,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 34203,
    physicalAttack = 1036,
    magicAttack = 1036,
    physicalDefence = 647,
    magicDefence = 647,
    hitLevel = 259,
    criticalLevel = 388,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 900,
    mPRecover = 900
    };
getRow(90)->
    #petLevelPropertyCfg {
    level = 90,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0,
    maxHP2 = 34567,
    physicalAttack = 1047,
    magicAttack = 1047,
    physicalDefence = 654,
    magicDefence = 654,
    hitLevel = 261,
    criticalLevel = 392,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 910,
    mPRecover = 910
    };
getRow(91)->
    #petLevelPropertyCfg {
    level = 91,
    maxHP = 47903,
    phyDef = 1703,
    holyDef = 1703,
    shadDef = 1703,
    eleDef = 1703,
    phycDam = 1596,
    holyDam = 1596,
    shadDam = 1596,
    eleDam = 0,
    maxHP2 = 34931,
    physicalAttack = 1058,
    magicAttack = 1058,
    physicalDefence = 661,
    magicDefence = 661,
    hitLevel = 264,
    criticalLevel = 396,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 920,
    mPRecover = 920
    };
getRow(92)->
    #petLevelPropertyCfg {
    level = 92,
    maxHP = 50424,
    phyDef = 1792,
    holyDef = 1792,
    shadDef = 1792,
    eleDef = 1792,
    phycDam = 1680,
    holyDam = 1680,
    shadDam = 1680,
    eleDam = 0,
    maxHP2 = 35295,
    physicalAttack = 1069,
    magicAttack = 1069,
    physicalDefence = 668,
    magicDefence = 668,
    hitLevel = 267,
    criticalLevel = 401,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 930,
    mPRecover = 930
    };
getRow(93)->
    #petLevelPropertyCfg {
    level = 93,
    maxHP = 53078,
    phyDef = 1887,
    holyDef = 1887,
    shadDef = 1887,
    eleDef = 1887,
    phycDam = 1769,
    holyDam = 1769,
    shadDam = 1769,
    eleDam = 0,
    maxHP2 = 35658,
    physicalAttack = 1080,
    magicAttack = 1080,
    physicalDefence = 675,
    magicDefence = 675,
    hitLevel = 270,
    criticalLevel = 405,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 940,
    mPRecover = 940
    };
getRow(94)->
    #petLevelPropertyCfg {
    level = 94,
    maxHP = 55871,
    phyDef = 1986,
    holyDef = 1986,
    shadDef = 1986,
    eleDef = 1986,
    phycDam = 1862,
    holyDam = 1862,
    shadDam = 1862,
    eleDam = 0,
    maxHP2 = 36022,
    physicalAttack = 1091,
    magicAttack = 1091,
    physicalDefence = 682,
    magicDefence = 682,
    hitLevel = 272,
    criticalLevel = 409,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 950,
    mPRecover = 950
    };
getRow(95)->
    #petLevelPropertyCfg {
    level = 95,
    maxHP = 58812,
    phyDef = 2091,
    holyDef = 2091,
    shadDef = 2091,
    eleDef = 2091,
    phycDam = 1960,
    holyDam = 1960,
    shadDam = 1960,
    eleDam = 0,
    maxHP2 = 36386,
    physicalAttack = 1102,
    magicAttack = 1102,
    physicalDefence = 689,
    magicDefence = 689,
    hitLevel = 275,
    criticalLevel = 413,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 960,
    mPRecover = 960
    };
getRow(96)->
    #petLevelPropertyCfg {
    level = 96,
    maxHP = 61907,
    phyDef = 2201,
    holyDef = 2201,
    shadDef = 2201,
    eleDef = 2201,
    phycDam = 2063,
    holyDam = 2063,
    shadDam = 2063,
    eleDam = 0,
    maxHP2 = 36750,
    physicalAttack = 1113,
    magicAttack = 1113,
    physicalDefence = 696,
    magicDefence = 696,
    hitLevel = 278,
    criticalLevel = 417,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 970,
    mPRecover = 970
    };
getRow(97)->
    #petLevelPropertyCfg {
    level = 97,
    maxHP = 65166,
    phyDef = 2317,
    holyDef = 2317,
    shadDef = 2317,
    eleDef = 2317,
    phycDam = 2172,
    holyDam = 2172,
    shadDam = 2172,
    eleDam = 0,
    maxHP2 = 37114,
    physicalAttack = 1124,
    magicAttack = 1124,
    physicalDefence = 702,
    magicDefence = 702,
    hitLevel = 281,
    criticalLevel = 421,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 980,
    mPRecover = 980
    };
getRow(98)->
    #petLevelPropertyCfg {
    level = 98,
    maxHP = 68596,
    phyDef = 2438,
    holyDef = 2438,
    shadDef = 2438,
    eleDef = 2438,
    phycDam = 2286,
    holyDam = 2286,
    shadDam = 2286,
    eleDam = 0,
    maxHP2 = 37478,
    physicalAttack = 1135,
    magicAttack = 1135,
    physicalDefence = 709,
    magicDefence = 709,
    hitLevel = 283,
    criticalLevel = 425,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 990,
    mPRecover = 990
    };
getRow(99)->
    #petLevelPropertyCfg {
    level = 99,
    maxHP = 72206,
    phyDef = 2567,
    holyDef = 2567,
    shadDef = 2567,
    eleDef = 2567,
    phycDam = 2406,
    holyDam = 2406,
    shadDam = 2406,
    eleDam = 0,
    maxHP2 = 37842,
    physicalAttack = 1146,
    magicAttack = 1146,
    physicalDefence = 716,
    magicDefence = 716,
    hitLevel = 286,
    criticalLevel = 430,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 1000,
    mPRecover = 1000
    };
getRow(100)->
    #petLevelPropertyCfg {
    level = 100,
    maxHP = 76006,
    phyDef = 2702,
    holyDef = 2702,
    shadDef = 2702,
    eleDef = 2702,
    phycDam = 2533,
    holyDam = 2533,
    shadDam = 2533,
    eleDam = 0,
    maxHP2 = 38206,
    physicalAttack = 1157,
    magicAttack = 1157,
    physicalDefence = 723,
    magicDefence = 723,
    hitLevel = 289,
    criticalLevel = 434,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 1010,
    mPRecover = 1010
    };
getRow(_)->[].

getKeyList()->[
    {1},
    {2},
    {3},
    {4},
    {5},
    {6},
    {7},
    {8},
    {9},
    {10},
    {11},
    {12},
    {13},
    {14},
    {15},
    {16},
    {17},
    {18},
    {19},
    {20},
    {21},
    {22},
    {23},
    {24},
    {25},
    {26},
    {27},
    {28},
    {29},
    {30},
    {31},
    {32},
    {33},
    {34},
    {35},
    {36},
    {37},
    {38},
    {39},
    {40},
    {41},
    {42},
    {43},
    {44},
    {45},
    {46},
    {47},
    {48},
    {49},
    {50},
    {51},
    {52},
    {53},
    {54},
    {55},
    {56},
    {57},
    {58},
    {59},
    {60},
    {61},
    {62},
    {63},
    {64},
    {65},
    {66},
    {67},
    {68},
    {69},
    {70},
    {71},
    {72},
    {73},
    {74},
    {75},
    {76},
    {77},
    {78},
    {79},
    {80},
    {81},
    {82},
    {83},
    {84},
    {85},
    {86},
    {87},
    {88},
    {89},
    {90},
    {91},
    {92},
    {93},
    {94},
    {95},
    {96},
    {97},
    {98},
    {99},
    {100}
    ].

get1KeyList()->[
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100
    ].

