%% coding: latin-1
%%: 实现
-module(cfg_petLevelProperty_chs).
-compile(export_all).
-include("cfg_petLevelProperty.hrl").
-include("logger.hrl").

getRow(1)->
    #petLevelPropertyCfg {
    level = 1,
    exp = 100,
    maxHP2 = 1200,
    physicalAttack = 120,
    magicAttack = 120,
    physicalDefence = 120,
    magicDefence = 120,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 20,
    mPRecover = 20,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(2)->
    #petLevelPropertyCfg {
    level = 2,
    exp = 200,
    maxHP2 = 150,
    physicalAttack = 15,
    magicAttack = 15,
    physicalDefence = 15,
    magicDefence = 15,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 10,
    mPRecover = 10,
    growLevel = 10,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(3)->
    #petLevelPropertyCfg {
    level = 3,
    exp = 300,
    maxHP2 = 500,
    physicalAttack = 50,
    magicAttack = 50,
    physicalDefence = 50,
    magicDefence = 50,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 40,
    mPRecover = 40,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(4)->
    #petLevelPropertyCfg {
    level = 4,
    exp = 400,
    maxHP2 = 550,
    physicalAttack = 55,
    magicAttack = 55,
    physicalDefence = 55,
    magicDefence = 55,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 50,
    mPRecover = 50,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(5)->
    #petLevelPropertyCfg {
    level = 5,
    exp = 500,
    maxHP2 = 600,
    physicalAttack = 60,
    magicAttack = 60,
    physicalDefence = 60,
    magicDefence = 60,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 60,
    mPRecover = 60,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(6)->
    #petLevelPropertyCfg {
    level = 6,
    exp = 600,
    maxHP2 = 650,
    physicalAttack = 65,
    magicAttack = 65,
    physicalDefence = 65,
    magicDefence = 65,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 70,
    mPRecover = 70,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(7)->
    #petLevelPropertyCfg {
    level = 7,
    exp = 700,
    maxHP2 = 700,
    physicalAttack = 70,
    magicAttack = 70,
    physicalDefence = 70,
    magicDefence = 70,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 80,
    mPRecover = 80,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(8)->
    #petLevelPropertyCfg {
    level = 8,
    exp = 800,
    maxHP2 = 750,
    physicalAttack = 75,
    magicAttack = 75,
    physicalDefence = 75,
    magicDefence = 75,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 90,
    mPRecover = 90,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(9)->
    #petLevelPropertyCfg {
    level = 9,
    exp = 900,
    maxHP2 = 800,
    physicalAttack = 80,
    magicAttack = 80,
    physicalDefence = 80,
    magicDefence = 80,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 100,
    mPRecover = 100,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(10)->
    #petLevelPropertyCfg {
    level = 10,
    exp = 1000,
    maxHP2 = 850,
    physicalAttack = 85,
    magicAttack = 85,
    physicalDefence = 85,
    magicDefence = 85,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 110,
    mPRecover = 110,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(11)->
    #petLevelPropertyCfg {
    level = 11,
    exp = 1100,
    maxHP2 = 900,
    physicalAttack = 90,
    magicAttack = 90,
    physicalDefence = 90,
    magicDefence = 90,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 120,
    mPRecover = 120,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(12)->
    #petLevelPropertyCfg {
    level = 12,
    exp = 1200,
    maxHP2 = 950,
    physicalAttack = 95,
    magicAttack = 95,
    physicalDefence = 95,
    magicDefence = 95,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 130,
    mPRecover = 130,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(13)->
    #petLevelPropertyCfg {
    level = 13,
    exp = 1300,
    maxHP2 = 1000,
    physicalAttack = 100,
    magicAttack = 100,
    physicalDefence = 100,
    magicDefence = 100,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 140,
    mPRecover = 140,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(14)->
    #petLevelPropertyCfg {
    level = 14,
    exp = 1400,
    maxHP2 = 1050,
    physicalAttack = 105,
    magicAttack = 105,
    physicalDefence = 105,
    magicDefence = 105,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 150,
    mPRecover = 150,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(15)->
    #petLevelPropertyCfg {
    level = 15,
    exp = 1500,
    maxHP2 = 1100,
    physicalAttack = 110,
    magicAttack = 110,
    physicalDefence = 110,
    magicDefence = 110,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 160,
    mPRecover = 160,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(16)->
    #petLevelPropertyCfg {
    level = 16,
    exp = 1600,
    maxHP2 = 1150,
    physicalAttack = 115,
    magicAttack = 115,
    physicalDefence = 115,
    magicDefence = 115,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 170,
    mPRecover = 170,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(17)->
    #petLevelPropertyCfg {
    level = 17,
    exp = 1700,
    maxHP2 = 1200,
    physicalAttack = 120,
    magicAttack = 120,
    physicalDefence = 120,
    magicDefence = 120,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 180,
    mPRecover = 180,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(18)->
    #petLevelPropertyCfg {
    level = 18,
    exp = 1800,
    maxHP2 = 1250,
    physicalAttack = 125,
    magicAttack = 125,
    physicalDefence = 125,
    magicDefence = 125,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 190,
    mPRecover = 190,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(19)->
    #petLevelPropertyCfg {
    level = 19,
    exp = 1900,
    maxHP2 = 1300,
    physicalAttack = 130,
    magicAttack = 130,
    physicalDefence = 130,
    magicDefence = 130,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 200,
    mPRecover = 200,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(20)->
    #petLevelPropertyCfg {
    level = 20,
    exp = 2000,
    maxHP2 = 1350,
    physicalAttack = 135,
    magicAttack = 135,
    physicalDefence = 135,
    magicDefence = 135,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 210,
    mPRecover = 210,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(21)->
    #petLevelPropertyCfg {
    level = 21,
    exp = 2100,
    maxHP2 = 1400,
    physicalAttack = 140,
    magicAttack = 140,
    physicalDefence = 140,
    magicDefence = 140,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 220,
    mPRecover = 220,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(22)->
    #petLevelPropertyCfg {
    level = 22,
    exp = 2200,
    maxHP2 = 1450,
    physicalAttack = 145,
    magicAttack = 145,
    physicalDefence = 145,
    magicDefence = 145,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 230,
    mPRecover = 230,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(23)->
    #petLevelPropertyCfg {
    level = 23,
    exp = 2300,
    maxHP2 = 1500,
    physicalAttack = 150,
    magicAttack = 150,
    physicalDefence = 150,
    magicDefence = 150,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 240,
    mPRecover = 240,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(24)->
    #petLevelPropertyCfg {
    level = 24,
    exp = 2400,
    maxHP2 = 1550,
    physicalAttack = 155,
    magicAttack = 155,
    physicalDefence = 155,
    magicDefence = 155,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 250,
    mPRecover = 250,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(25)->
    #petLevelPropertyCfg {
    level = 25,
    exp = 2500,
    maxHP2 = 1600,
    physicalAttack = 160,
    magicAttack = 160,
    physicalDefence = 160,
    magicDefence = 160,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 260,
    mPRecover = 260,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(26)->
    #petLevelPropertyCfg {
    level = 26,
    exp = 2600,
    maxHP2 = 1650,
    physicalAttack = 165,
    magicAttack = 165,
    physicalDefence = 165,
    magicDefence = 165,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 270,
    mPRecover = 270,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(27)->
    #petLevelPropertyCfg {
    level = 27,
    exp = 2700,
    maxHP2 = 1700,
    physicalAttack = 170,
    magicAttack = 170,
    physicalDefence = 170,
    magicDefence = 170,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 280,
    mPRecover = 280,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(28)->
    #petLevelPropertyCfg {
    level = 28,
    exp = 2800,
    maxHP2 = 1750,
    physicalAttack = 175,
    magicAttack = 175,
    physicalDefence = 175,
    magicDefence = 175,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 290,
    mPRecover = 290,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(29)->
    #petLevelPropertyCfg {
    level = 29,
    exp = 2900,
    maxHP2 = 1800,
    physicalAttack = 180,
    magicAttack = 180,
    physicalDefence = 180,
    magicDefence = 180,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 300,
    mPRecover = 300,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(30)->
    #petLevelPropertyCfg {
    level = 30,
    exp = 3000,
    maxHP2 = 1850,
    physicalAttack = 185,
    magicAttack = 185,
    physicalDefence = 185,
    magicDefence = 185,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 310,
    mPRecover = 310,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(31)->
    #petLevelPropertyCfg {
    level = 31,
    exp = 3100,
    maxHP2 = 1900,
    physicalAttack = 190,
    magicAttack = 190,
    physicalDefence = 190,
    magicDefence = 190,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 320,
    mPRecover = 320,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(32)->
    #petLevelPropertyCfg {
    level = 32,
    exp = 3200,
    maxHP2 = 1950,
    physicalAttack = 195,
    magicAttack = 195,
    physicalDefence = 195,
    magicDefence = 195,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 330,
    mPRecover = 330,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(33)->
    #petLevelPropertyCfg {
    level = 33,
    exp = 3300,
    maxHP2 = 2000,
    physicalAttack = 200,
    magicAttack = 200,
    physicalDefence = 200,
    magicDefence = 200,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 340,
    mPRecover = 340,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(34)->
    #petLevelPropertyCfg {
    level = 34,
    exp = 3400,
    maxHP2 = 2050,
    physicalAttack = 205,
    magicAttack = 205,
    physicalDefence = 205,
    magicDefence = 205,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 350,
    mPRecover = 350,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(35)->
    #petLevelPropertyCfg {
    level = 35,
    exp = 3500,
    maxHP2 = 2100,
    physicalAttack = 210,
    magicAttack = 210,
    physicalDefence = 210,
    magicDefence = 210,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 360,
    mPRecover = 360,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(36)->
    #petLevelPropertyCfg {
    level = 36,
    exp = 3600,
    maxHP2 = 2150,
    physicalAttack = 215,
    magicAttack = 215,
    physicalDefence = 215,
    magicDefence = 215,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 370,
    mPRecover = 370,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(37)->
    #petLevelPropertyCfg {
    level = 37,
    exp = 3700,
    maxHP2 = 2200,
    physicalAttack = 220,
    magicAttack = 220,
    physicalDefence = 220,
    magicDefence = 220,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 380,
    mPRecover = 380,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(38)->
    #petLevelPropertyCfg {
    level = 38,
    exp = 3800,
    maxHP2 = 2250,
    physicalAttack = 225,
    magicAttack = 225,
    physicalDefence = 225,
    magicDefence = 225,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 390,
    mPRecover = 390,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(39)->
    #petLevelPropertyCfg {
    level = 39,
    exp = 3900,
    maxHP2 = 2300,
    physicalAttack = 230,
    magicAttack = 230,
    physicalDefence = 230,
    magicDefence = 230,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 400,
    mPRecover = 400,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(40)->
    #petLevelPropertyCfg {
    level = 40,
    exp = 4000,
    maxHP2 = 2350,
    physicalAttack = 235,
    magicAttack = 235,
    physicalDefence = 235,
    magicDefence = 235,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 410,
    mPRecover = 410,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(41)->
    #petLevelPropertyCfg {
    level = 41,
    exp = 4100,
    maxHP2 = 2400,
    physicalAttack = 240,
    magicAttack = 240,
    physicalDefence = 240,
    magicDefence = 240,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 420,
    mPRecover = 420,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(42)->
    #petLevelPropertyCfg {
    level = 42,
    exp = 4200,
    maxHP2 = 2450,
    physicalAttack = 245,
    magicAttack = 245,
    physicalDefence = 245,
    magicDefence = 245,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 430,
    mPRecover = 430,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(43)->
    #petLevelPropertyCfg {
    level = 43,
    exp = 4300,
    maxHP2 = 2500,
    physicalAttack = 250,
    magicAttack = 250,
    physicalDefence = 250,
    magicDefence = 250,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 440,
    mPRecover = 440,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(44)->
    #petLevelPropertyCfg {
    level = 44,
    exp = 4400,
    maxHP2 = 2550,
    physicalAttack = 255,
    magicAttack = 255,
    physicalDefence = 255,
    magicDefence = 255,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 450,
    mPRecover = 450,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(45)->
    #petLevelPropertyCfg {
    level = 45,
    exp = 4500,
    maxHP2 = 2600,
    physicalAttack = 260,
    magicAttack = 260,
    physicalDefence = 260,
    magicDefence = 260,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 460,
    mPRecover = 460,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(46)->
    #petLevelPropertyCfg {
    level = 46,
    exp = 4600,
    maxHP2 = 2650,
    physicalAttack = 265,
    magicAttack = 265,
    physicalDefence = 265,
    magicDefence = 265,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 470,
    mPRecover = 470,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(47)->
    #petLevelPropertyCfg {
    level = 47,
    exp = 4700,
    maxHP2 = 2700,
    physicalAttack = 270,
    magicAttack = 270,
    physicalDefence = 270,
    magicDefence = 270,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 480,
    mPRecover = 480,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(48)->
    #petLevelPropertyCfg {
    level = 48,
    exp = 4800,
    maxHP2 = 2750,
    physicalAttack = 275,
    magicAttack = 275,
    physicalDefence = 275,
    magicDefence = 275,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 490,
    mPRecover = 490,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(49)->
    #petLevelPropertyCfg {
    level = 49,
    exp = 4900,
    maxHP2 = 2800,
    physicalAttack = 280,
    magicAttack = 280,
    physicalDefence = 280,
    magicDefence = 280,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 500,
    mPRecover = 500,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(50)->
    #petLevelPropertyCfg {
    level = 50,
    exp = 5000,
    maxHP2 = 2850,
    physicalAttack = 285,
    magicAttack = 285,
    physicalDefence = 285,
    magicDefence = 285,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 510,
    mPRecover = 510,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(51)->
    #petLevelPropertyCfg {
    level = 51,
    exp = 5100,
    maxHP2 = 2900,
    physicalAttack = 290,
    magicAttack = 290,
    physicalDefence = 290,
    magicDefence = 290,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 520,
    mPRecover = 520,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(52)->
    #petLevelPropertyCfg {
    level = 52,
    exp = 5200,
    maxHP2 = 2950,
    physicalAttack = 295,
    magicAttack = 295,
    physicalDefence = 295,
    magicDefence = 295,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 530,
    mPRecover = 530,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(53)->
    #petLevelPropertyCfg {
    level = 53,
    exp = 5300,
    maxHP2 = 3000,
    physicalAttack = 300,
    magicAttack = 300,
    physicalDefence = 300,
    magicDefence = 300,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 540,
    mPRecover = 540,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(54)->
    #petLevelPropertyCfg {
    level = 54,
    exp = 5400,
    maxHP2 = 3050,
    physicalAttack = 305,
    magicAttack = 305,
    physicalDefence = 305,
    magicDefence = 305,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 550,
    mPRecover = 550,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(55)->
    #petLevelPropertyCfg {
    level = 55,
    exp = 5500,
    maxHP2 = 3100,
    physicalAttack = 310,
    magicAttack = 310,
    physicalDefence = 310,
    magicDefence = 310,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 560,
    mPRecover = 560,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(56)->
    #petLevelPropertyCfg {
    level = 56,
    exp = 5600,
    maxHP2 = 3150,
    physicalAttack = 315,
    magicAttack = 315,
    physicalDefence = 315,
    magicDefence = 315,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 570,
    mPRecover = 570,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(57)->
    #petLevelPropertyCfg {
    level = 57,
    exp = 5700,
    maxHP2 = 3200,
    physicalAttack = 320,
    magicAttack = 320,
    physicalDefence = 320,
    magicDefence = 320,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 580,
    mPRecover = 580,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(58)->
    #petLevelPropertyCfg {
    level = 58,
    exp = 5800,
    maxHP2 = 3250,
    physicalAttack = 325,
    magicAttack = 325,
    physicalDefence = 325,
    magicDefence = 325,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 590,
    mPRecover = 590,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(59)->
    #petLevelPropertyCfg {
    level = 59,
    exp = 5900,
    maxHP2 = 3300,
    physicalAttack = 330,
    magicAttack = 330,
    physicalDefence = 330,
    magicDefence = 330,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 600,
    mPRecover = 600,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(60)->
    #petLevelPropertyCfg {
    level = 60,
    exp = 6000,
    maxHP2 = 3350,
    physicalAttack = 335,
    magicAttack = 335,
    physicalDefence = 335,
    magicDefence = 335,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 610,
    mPRecover = 610,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(61)->
    #petLevelPropertyCfg {
    level = 61,
    exp = 6100,
    maxHP2 = 3400,
    physicalAttack = 340,
    magicAttack = 340,
    physicalDefence = 340,
    magicDefence = 340,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 620,
    mPRecover = 620,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(62)->
    #petLevelPropertyCfg {
    level = 62,
    exp = 6200,
    maxHP2 = 3450,
    physicalAttack = 345,
    magicAttack = 345,
    physicalDefence = 345,
    magicDefence = 345,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 630,
    mPRecover = 630,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(63)->
    #petLevelPropertyCfg {
    level = 63,
    exp = 6300,
    maxHP2 = 3500,
    physicalAttack = 350,
    magicAttack = 350,
    physicalDefence = 350,
    magicDefence = 350,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 640,
    mPRecover = 640,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(64)->
    #petLevelPropertyCfg {
    level = 64,
    exp = 6400,
    maxHP2 = 3550,
    physicalAttack = 355,
    magicAttack = 355,
    physicalDefence = 355,
    magicDefence = 355,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 650,
    mPRecover = 650,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(65)->
    #petLevelPropertyCfg {
    level = 65,
    exp = 6500,
    maxHP2 = 3600,
    physicalAttack = 360,
    magicAttack = 360,
    physicalDefence = 360,
    magicDefence = 360,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 660,
    mPRecover = 660,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(66)->
    #petLevelPropertyCfg {
    level = 66,
    exp = 6600,
    maxHP2 = 3650,
    physicalAttack = 365,
    magicAttack = 365,
    physicalDefence = 365,
    magicDefence = 365,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 670,
    mPRecover = 670,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(67)->
    #petLevelPropertyCfg {
    level = 67,
    exp = 6700,
    maxHP2 = 3700,
    physicalAttack = 370,
    magicAttack = 370,
    physicalDefence = 370,
    magicDefence = 370,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 680,
    mPRecover = 680,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(68)->
    #petLevelPropertyCfg {
    level = 68,
    exp = 6800,
    maxHP2 = 3750,
    physicalAttack = 375,
    magicAttack = 375,
    physicalDefence = 375,
    magicDefence = 375,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 690,
    mPRecover = 690,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(69)->
    #petLevelPropertyCfg {
    level = 69,
    exp = 6900,
    maxHP2 = 3800,
    physicalAttack = 380,
    magicAttack = 380,
    physicalDefence = 380,
    magicDefence = 380,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 700,
    mPRecover = 700,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(70)->
    #petLevelPropertyCfg {
    level = 70,
    exp = 7000,
    maxHP2 = 3850,
    physicalAttack = 385,
    magicAttack = 385,
    physicalDefence = 385,
    magicDefence = 385,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 710,
    mPRecover = 710,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(71)->
    #petLevelPropertyCfg {
    level = 71,
    exp = 7100,
    maxHP2 = 3900,
    physicalAttack = 390,
    magicAttack = 390,
    physicalDefence = 390,
    magicDefence = 390,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 720,
    mPRecover = 720,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(72)->
    #petLevelPropertyCfg {
    level = 72,
    exp = 7200,
    maxHP2 = 3950,
    physicalAttack = 395,
    magicAttack = 395,
    physicalDefence = 395,
    magicDefence = 395,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 730,
    mPRecover = 730,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(73)->
    #petLevelPropertyCfg {
    level = 73,
    exp = 7300,
    maxHP2 = 4000,
    physicalAttack = 400,
    magicAttack = 400,
    physicalDefence = 400,
    magicDefence = 400,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 740,
    mPRecover = 740,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(74)->
    #petLevelPropertyCfg {
    level = 74,
    exp = 7400,
    maxHP2 = 4050,
    physicalAttack = 405,
    magicAttack = 405,
    physicalDefence = 405,
    magicDefence = 405,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 750,
    mPRecover = 750,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(75)->
    #petLevelPropertyCfg {
    level = 75,
    exp = 7500,
    maxHP2 = 4100,
    physicalAttack = 410,
    magicAttack = 410,
    physicalDefence = 410,
    magicDefence = 410,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 760,
    mPRecover = 760,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(76)->
    #petLevelPropertyCfg {
    level = 76,
    exp = 7600,
    maxHP2 = 4150,
    physicalAttack = 415,
    magicAttack = 415,
    physicalDefence = 415,
    magicDefence = 415,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 770,
    mPRecover = 770,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(77)->
    #petLevelPropertyCfg {
    level = 77,
    exp = 7700,
    maxHP2 = 4200,
    physicalAttack = 420,
    magicAttack = 420,
    physicalDefence = 420,
    magicDefence = 420,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 780,
    mPRecover = 780,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(78)->
    #petLevelPropertyCfg {
    level = 78,
    exp = 7800,
    maxHP2 = 4250,
    physicalAttack = 425,
    magicAttack = 425,
    physicalDefence = 425,
    magicDefence = 425,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 790,
    mPRecover = 790,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(79)->
    #petLevelPropertyCfg {
    level = 79,
    exp = 7900,
    maxHP2 = 4300,
    physicalAttack = 430,
    magicAttack = 430,
    physicalDefence = 430,
    magicDefence = 430,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 800,
    mPRecover = 800,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(80)->
    #petLevelPropertyCfg {
    level = 80,
    exp = 8000,
    maxHP2 = 4350,
    physicalAttack = 435,
    magicAttack = 435,
    physicalDefence = 435,
    magicDefence = 435,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 810,
    mPRecover = 810,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(81)->
    #petLevelPropertyCfg {
    level = 81,
    exp = 8100,
    maxHP2 = 4400,
    physicalAttack = 440,
    magicAttack = 440,
    physicalDefence = 440,
    magicDefence = 440,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 820,
    mPRecover = 820,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(82)->
    #petLevelPropertyCfg {
    level = 82,
    exp = 8200,
    maxHP2 = 4450,
    physicalAttack = 445,
    magicAttack = 445,
    physicalDefence = 445,
    magicDefence = 445,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 830,
    mPRecover = 830,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(83)->
    #petLevelPropertyCfg {
    level = 83,
    exp = 8300,
    maxHP2 = 4500,
    physicalAttack = 450,
    magicAttack = 450,
    physicalDefence = 450,
    magicDefence = 450,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 840,
    mPRecover = 840,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(84)->
    #petLevelPropertyCfg {
    level = 84,
    exp = 8400,
    maxHP2 = 4550,
    physicalAttack = 455,
    magicAttack = 455,
    physicalDefence = 455,
    magicDefence = 455,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 850,
    mPRecover = 850,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(85)->
    #petLevelPropertyCfg {
    level = 85,
    exp = 8500,
    maxHP2 = 4600,
    physicalAttack = 460,
    magicAttack = 460,
    physicalDefence = 460,
    magicDefence = 460,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 860,
    mPRecover = 860,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(86)->
    #petLevelPropertyCfg {
    level = 86,
    exp = 8600,
    maxHP2 = 4650,
    physicalAttack = 465,
    magicAttack = 465,
    physicalDefence = 465,
    magicDefence = 465,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 870,
    mPRecover = 870,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(87)->
    #petLevelPropertyCfg {
    level = 87,
    exp = 8700,
    maxHP2 = 4700,
    physicalAttack = 470,
    magicAttack = 470,
    physicalDefence = 470,
    magicDefence = 470,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 880,
    mPRecover = 880,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(88)->
    #petLevelPropertyCfg {
    level = 88,
    exp = 8800,
    maxHP2 = 4750,
    physicalAttack = 475,
    magicAttack = 475,
    physicalDefence = 475,
    magicDefence = 475,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 890,
    mPRecover = 890,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(89)->
    #petLevelPropertyCfg {
    level = 89,
    exp = 8900,
    maxHP2 = 4800,
    physicalAttack = 480,
    magicAttack = 480,
    physicalDefence = 480,
    magicDefence = 480,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 900,
    mPRecover = 900,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(90)->
    #petLevelPropertyCfg {
    level = 90,
    exp = 9000,
    maxHP2 = 4850,
    physicalAttack = 485,
    magicAttack = 485,
    physicalDefence = 485,
    magicDefence = 485,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 910,
    mPRecover = 910,
    growLevel = 0,
    maxHP = 0,
    phyDef = 0,
    holyDef = 0,
    shadDef = 0,
    eleDef = 0,
    phycDam = 0,
    holyDam = 0,
    shadDam = 0,
    eleDam = 0
    };
getRow(91)->
    #petLevelPropertyCfg {
    level = 91,
    exp = 9100,
    maxHP2 = 4900,
    physicalAttack = 490,
    magicAttack = 490,
    physicalDefence = 490,
    magicDefence = 490,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 920,
    mPRecover = 920,
    growLevel = 0,
    maxHP = 47903,
    phyDef = 1703,
    holyDef = 1703,
    shadDef = 1703,
    eleDef = 1703,
    phycDam = 1596,
    holyDam = 1596,
    shadDam = 1596,
    eleDam = 0
    };
getRow(92)->
    #petLevelPropertyCfg {
    level = 92,
    exp = 9200,
    maxHP2 = 4950,
    physicalAttack = 495,
    magicAttack = 495,
    physicalDefence = 495,
    magicDefence = 495,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 930,
    mPRecover = 930,
    growLevel = 0,
    maxHP = 50424,
    phyDef = 1792,
    holyDef = 1792,
    shadDef = 1792,
    eleDef = 1792,
    phycDam = 1680,
    holyDam = 1680,
    shadDam = 1680,
    eleDam = 0
    };
getRow(93)->
    #petLevelPropertyCfg {
    level = 93,
    exp = 9300,
    maxHP2 = 5000,
    physicalAttack = 500,
    magicAttack = 500,
    physicalDefence = 500,
    magicDefence = 500,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 940,
    mPRecover = 940,
    growLevel = 0,
    maxHP = 53078,
    phyDef = 1887,
    holyDef = 1887,
    shadDef = 1887,
    eleDef = 1887,
    phycDam = 1769,
    holyDam = 1769,
    shadDam = 1769,
    eleDam = 0
    };
getRow(94)->
    #petLevelPropertyCfg {
    level = 94,
    exp = 9400,
    maxHP2 = 5050,
    physicalAttack = 505,
    magicAttack = 505,
    physicalDefence = 505,
    magicDefence = 505,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 950,
    mPRecover = 950,
    growLevel = 0,
    maxHP = 55871,
    phyDef = 1986,
    holyDef = 1986,
    shadDef = 1986,
    eleDef = 1986,
    phycDam = 1862,
    holyDam = 1862,
    shadDam = 1862,
    eleDam = 0
    };
getRow(95)->
    #petLevelPropertyCfg {
    level = 95,
    exp = 9500,
    maxHP2 = 5100,
    physicalAttack = 510,
    magicAttack = 510,
    physicalDefence = 510,
    magicDefence = 510,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 960,
    mPRecover = 960,
    growLevel = 0,
    maxHP = 58812,
    phyDef = 2091,
    holyDef = 2091,
    shadDef = 2091,
    eleDef = 2091,
    phycDam = 1960,
    holyDam = 1960,
    shadDam = 1960,
    eleDam = 0
    };
getRow(96)->
    #petLevelPropertyCfg {
    level = 96,
    exp = 9600,
    maxHP2 = 5150,
    physicalAttack = 515,
    magicAttack = 515,
    physicalDefence = 515,
    magicDefence = 515,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 970,
    mPRecover = 970,
    growLevel = 0,
    maxHP = 61907,
    phyDef = 2201,
    holyDef = 2201,
    shadDef = 2201,
    eleDef = 2201,
    phycDam = 2063,
    holyDam = 2063,
    shadDam = 2063,
    eleDam = 0
    };
getRow(97)->
    #petLevelPropertyCfg {
    level = 97,
    exp = 9700,
    maxHP2 = 5200,
    physicalAttack = 520,
    magicAttack = 520,
    physicalDefence = 520,
    magicDefence = 520,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 980,
    mPRecover = 980,
    growLevel = 0,
    maxHP = 65166,
    phyDef = 2317,
    holyDef = 2317,
    shadDef = 2317,
    eleDef = 2317,
    phycDam = 2172,
    holyDam = 2172,
    shadDam = 2172,
    eleDam = 0
    };
getRow(98)->
    #petLevelPropertyCfg {
    level = 98,
    exp = 9800,
    maxHP2 = 5250,
    physicalAttack = 525,
    magicAttack = 525,
    physicalDefence = 525,
    magicDefence = 525,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 990,
    mPRecover = 990,
    growLevel = 0,
    maxHP = 68596,
    phyDef = 2438,
    holyDef = 2438,
    shadDef = 2438,
    eleDef = 2438,
    phycDam = 2286,
    holyDam = 2286,
    shadDam = 2286,
    eleDam = 0
    };
getRow(99)->
    #petLevelPropertyCfg {
    level = 99,
    exp = 9900,
    maxHP2 = 5300,
    physicalAttack = 530,
    magicAttack = 530,
    physicalDefence = 530,
    magicDefence = 530,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 1000,
    mPRecover = 1000,
    growLevel = 0,
    maxHP = 72206,
    phyDef = 2567,
    holyDef = 2567,
    shadDef = 2567,
    eleDef = 2567,
    phycDam = 2406,
    holyDam = 2406,
    shadDam = 2406,
    eleDam = 0
    };
getRow(100)->
    #petLevelPropertyCfg {
    level = 100,
    exp = 10000,
    maxHP2 = 5350,
    physicalAttack = 535,
    magicAttack = 535,
    physicalDefence = 535,
    magicDefence = 535,
    hitLevel = 0,
    criticalLevel = 0,
    criticalDamageLevel = 0,
    armorPenetrationLevel = 0,
    dodgeLevel = 0,
    criticalResistLevel = 0,
    tenaciousLevel = 0,
    hPRecover = 1010,
    mPRecover = 1010,
    growLevel = 0,
    maxHP = 76006,
    phyDef = 2702,
    holyDef = 2702,
    shadDef = 2702,
    eleDef = 2702,
    phycDam = 2533,
    holyDam = 2533,
    shadDam = 2533,
    eleDam = 0
    };
getRow(_)->[].

getKeyList()->[
    {1},
    {2},
    {3},
    {4},
    {5},
    {6},
    {7},
    {8},
    {9},
    {10},
    {11},
    {12},
    {13},
    {14},
    {15},
    {16},
    {17},
    {18},
    {19},
    {20},
    {21},
    {22},
    {23},
    {24},
    {25},
    {26},
    {27},
    {28},
    {29},
    {30},
    {31},
    {32},
    {33},
    {34},
    {35},
    {36},
    {37},
    {38},
    {39},
    {40},
    {41},
    {42},
    {43},
    {44},
    {45},
    {46},
    {47},
    {48},
    {49},
    {50},
    {51},
    {52},
    {53},
    {54},
    {55},
    {56},
    {57},
    {58},
    {59},
    {60},
    {61},
    {62},
    {63},
    {64},
    {65},
    {66},
    {67},
    {68},
    {69},
    {70},
    {71},
    {72},
    {73},
    {74},
    {75},
    {76},
    {77},
    {78},
    {79},
    {80},
    {81},
    {82},
    {83},
    {84},
    {85},
    {86},
    {87},
    {88},
    {89},
    {90},
    {91},
    {92},
    {93},
    {94},
    {95},
    {96},
    {97},
    {98},
    {99},
    {100}
    ].

get1KeyList()->[
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100
    ].

